[package]
edition = "2021"
name = "service_runner"
version = "0.1.0"

[dependencies]
clap = {workspace = true}
color-eyre = {workspace = true}
dotenv = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
